[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "codeql-miner"
version = "0.1.0"
dependencies = [
    "typer[all]",
    "pydantic",
    "requests",
    "gitpython",
    "pytest"
]

[project.scripts]
miner = "miner.cli:app"

[tool.setuptools.packages.find]
where = ["src"]